<!-- html -->
<template>
  <m-space>
    <i-button>按钮</i-button>
    <i-button>按钮</i-button>
    <i-button>按钮</i-button>
    <i-button>按钮</i-button>
    <i-button>按钮</i-button>
    <i-button>按钮</i-button>
    <i-button>按钮</i-button>
    <i-button>按钮</i-button>
    <i-button>按钮</i-button>
    <i-button>按钮</i-button>
    <i-button>按钮</i-button>
    <i-button>按钮</i-button>
    <i-button>按钮</i-button>
    <i-button>按钮</i-button>
    <i-button>按钮</i-button>
    <i-button>按钮</i-button>
  </m-space>
</template>