<!-- html -->
<template>
  <m-space :size="[10, 10]">
    <i-button>按钮</i-button>
    <i-button>按钮</i-button>
    <i-button>按钮</i-button>
    <i-button>按钮</i-button>
    <i-button>按钮</i-button>
    <i-button>按钮</i-button>
    <i-button>按钮</i-button>
    <i-button>按钮</i-button>
    <i-button>按钮</i-button>
    <i-button>按钮</i-button>
    <i-button>按钮</i-button>
    <i-button>按钮</i-button>
    <i-button>按钮</i-button>
    <i-button>按钮</i-button>
    <i-button>按钮</i-button>
    <i-button>按钮</i-button>
    <i-button>按钮</i-button>
    <i-button>按钮</i-button>
    <i-button>按钮</i-button>
    <i-button>按钮</i-button>
    <i-button>按钮</i-button>
    <i-button>按钮</i-button>
    <i-button>按钮</i-button>
    <i-button>按钮</i-button>
    <i-button>按钮</i-button>
    <i-button>按钮</i-button>
  </m-space>
</template>