<!-- html -->
<template>
  <i-space>
    <i-button>按钮</i-button>
    <i-button>按钮</i-button>
    <i-button>按钮</i-button>
    <i-button>按钮</i-button>
    <i-button>按钮</i-button>
    <i-button>按钮</i-button>
    <i-button>按钮</i-button>
    <i-button>按钮</i-button>
    <i-button>按钮</i-button>
    <i-button>按钮</i-button>
    <i-button>按钮</i-button>
    <i-button>按钮</i-button>
    <i-button>按钮</i-button>
    <i-button>按钮</i-button>
    <i-button>按钮</i-button>
    <i-button>按钮</i-button>
  </i-space>
</template>